const curr_env = process.env.VITE_ENV
const prod_backend_url = process.env.VITE_BACKEND_URL
export const baseUrl = curr_env == 'dev' ? "http://localhost:8080/api/v1" : `${prod_backend_url}/api/v1`;
// console.log();
export const apis = {
    authenticate: `${baseUrl}/auth/authenticate-user`,
    register: `${baseUrl}/auth/register-student`,
    verifyCode: `${baseUrl}/auth/verify-code`,
    sendResetToken: `${baseUrl}/auth/reset-request`,
    confirmToken: `${baseUrl}/auth/confirm-token`,
    resetPassword: `${baseUrl}/auth/reset-password`,
    registerAdmin: `${baseUrl}/admin/register-admin`,
    registerDrive: `${baseUrl}/admin/register-drive`,
    getAllDrive: `${baseUrl}/admin/get-drives`,
    getAllCurrentDrive: `${baseUrl}/admin/get-drives-current`,
    getUnfinished: `${baseUrl}/admin/get-unfinished-drives`,
    getFinished: `${baseUrl}/admin/get-finished-drives`,
    getStudentsOffer: `${baseUrl}/student/get-student-offer`,
    getAllCurrentDrive: `${baseUrl}/admin/get-drives-current`,
    deleteDrive: `${baseUrl}/admin/delete-drive`,
    getDrive: `${baseUrl}/admin/get-drive`,
    updateDrive: `${baseUrl}/admin/update-drive`,
    getStudents: `${baseUrl}/admin/get-students`,
    deleteStudent: `${baseUrl}/admin/delete-student`,
    getStudentByAdmin: `${baseUrl}/admin/get-student`,
    getStudentSkillByAdmin:`${baseUrl}/admin/get-skills`,
    getStudentEducationByAdmin:`${baseUrl}/admin/get-education`,
    getStudentExperienceByAdmin:`${baseUrl}/admin/get-experience`,
    getStudentProjectByAdmin: `${baseUrl}/admin/get-project`,
    getAllPendingApplications:`${baseUrl}/admin/get-pending-application`,
    approveApplication: `${baseUrl}/admin/approve-application`,
    rejectApplication: `${baseUrl}/admin/reject-application`,
    sendNotification: `${baseUrl}/admin/send-notifications`,
    getDriveApplication: `${baseUrl}/admin/get-applications`,
    getDriveStudent: `${baseUrl}/student/get-drive`,
    getAllDriveStudent: `${baseUrl}/student/get-drives`,
    getStudentApplication: `${baseUrl}/student/get-status`,
    registerApplication: `${baseUrl}/student/register-application`,
    deleteApplication: `${baseUrl}/student/delete-application`,
    getStudent: `${baseUrl}/student/get-student`,
    getStudentData: `${baseUrl}/student/get-student-data`,
    getAllSkills: `${baseUrl}/student/get-skills`,
    getStudentSkills: `${baseUrl}/student/get-skills`,
    getSkillByName: `${baseUrl}/student/get-by-skill-name`,
    registerSkill: `${baseUrl}/student/register-skill`,
    registerStudentSkill: `${baseUrl}/student/register-student-skill`,
    deleteStudentSkill: `${baseUrl}/student/delete-student-skill`,
    registerEducation:`${baseUrl}/student/register-education`,
    updateEducation: `${baseUrl}/student/update-education`,
    getAllEducations: `${baseUrl}/student/get-education`,
    deleteEducation: `${baseUrl}/student/delete-education`,
    getAllExperiences: `${baseUrl}/student/get-experience`,
    registerExperience: `${baseUrl}/student/register-experience`,
    updateExperience: `${baseUrl}/student/update-experience`,
    deleteExperience: `${baseUrl}/student/delete-experience`,
    getAllProjects: `${baseUrl}/student/get-project`,
    deleteProject: `${baseUrl}/student/delete-project`,
    updateProject: `${baseUrl}/student/update-project`,
    registerProject: `${baseUrl}/student/register-project`,
    getAllApplications: `${baseUrl}/student/get-applications`,
    getStudentCount: `${baseUrl}/statistic/get-student-count`,
    getDriveCount: `${baseUrl}/statistic/get-drive-count`,
    getApplicationsCount: `${baseUrl}/statistic/get-application-count`,
    getPendingApplicationCount: `${baseUrl}/statistic/get-pending-application-count`,
    getStudentApplicationCount: `${baseUrl}/statistic/get-students-application-count`,
    getStudentPendingApplicationCount: `${baseUrl}/statistic/get-students-pending-application-count`,
    placeStudents: `${baseUrl}/admin/place-students`
}

export default apis;